
all : 
	javac -deprecation -d /users/ca4/tdoris.ca4/BCK/classes *.java

run :
	java -classpath .:/app1/lang/jdk/lib/classes.zip:/users/ca4/tdoris.ca4/BCK/classes BCK.ANN.BCKDriver

clean :
	rm /users/ca4/tdoris.ca4/BCK/classes/BCK/ANN/*.class
