
all : 
	javac -deprecation -d /users/ca4/tdoris.ca4/BCK/classes *.java

clean :
	rm -fr /users/ca4/tdoris.ca4/BCK/classes/BCK/GUI/*.class
run :
	java -DBCK.home=/users/ca4/tdoris.ca4/BCK/classes/BCK/GUI/ -mx100m -oss1m -ss1m -ms10m BCK.GUI.bck


